### ISSUE TITLE
submit script failed if script is a path

### ISSUE THREAD

**Issue by guillaume-philippon** [LAL/Condor-Tools#3]
[philippo@lhcb3 ~/condor]$ condor.py --machine lx4.lal.in2p3.fr --group si condor/myexec
Traceback (most recent call last):
  File "/opt/lal/bin/condor.py", line 117, in <module>
    main()
  File "/opt/lal/bin/condor.py", line 108, in main
    directory = prepare_job_execution(arguments.script)
  File "/opt/lal/bin/condor.py", line 98, in prepare_job_execution
    os.mkdir(directory_name)
OSError: [Errno 2] No such file or directory: 'condor/myexec.1428047498.68'

**Comment by guillaume-philippon** [comment]
Fixed by PR #5
